name: Generate Changelogs from Other Repos

on:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Clone other repositories
        run: |
          git clone https://github.com/sevifinance/Sevi-Admin-g ./other-repo-1
          git clone https://github.com/sevifinance/Sevi-Mobile ./other-repo-2

      - name: Generate changelog for other-repo-1
        run: |
          cd ./other-repo-1
          npm install
          npx semantic-release --dry-run > ../changelog-other-repo-1.md
          cd ..

      - name: Generate changelog for other-repo-2
        run: |
          cd ./other-repo-2
          npm install
          npx semantic-release --dry-run > ../changelog-other-repo-2.md
          cd ..

      - name: Combine changelogs
        run: |
          echo "# Combined Changelog" > combined-changelog.md
          echo "\n## Changelog for other-repo-1" >> combined-changelog.md
          cat changelog-other-repo-1.md >> combined-changelog.md
          echo "\n## Changelog for other-repo-2" >> combined-changelog.md
          cat changelog-other-repo-2.md >> combined-changelog.md

      - name: Commit changelogs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add combined-changelog.md
          git commit -m "chore: update combined changelog"
          git push origin main