name: Generate Changelogs from Other Repos

on:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Clone other repositories
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://${GH_PAT}@github.com/sevifinance/Sevi-Admin-g.git ./other-repo-1
        #   git clone https://${GH_PAT}@github.com/sevifinance/Sevi-Mobile.git ./other-repo-2

      - name: Generate changelog for other-repo-1
        run: |
          cd ./other-repo-1
          git fetch --all
          git checkout shadcn
          npx conventional-changelog -i CHANGELOG.md -s
          mv CHANGELOG.md ../changelog-other-repo-1.md
          cd ..

    #   - name: Generate changelog for other-repo-2
    #     run: |
    #       cd ./other-repo-2
    #       git fetch --all
    #       git checkout staging
    #       npx semantic-release --branches staging
    #       npx conventional-changelog -p angular -i CHANGELOG.md -s
    #       mv CHANGELOG.md ../changelog-other-repo-2.md
    #       cd ..

      - name: Save changelogs
        run: |
          if [ -s changelog-other-repo-1.md ]; then
            mv changelog-other-repo-1.md changelog-repo-1.md
          else
            echo "No changes detected for other-repo-1" > changelog-repo-1.md
          fi
          
          if [ -s changelog-other-repo-2.md ]; then
            mv changelog-other-repo-2.md changelog-repo-2.md
          else
            echo "No changes detected for other-repo-2" > changelog-repo-2.md
          fi

          
      - name: Commit changelogs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add changelog-repo-1.md changelog-repo-2.md
          git commit -m "chore: update combined changelog"
          git push origin main
